### ISSUE TITLE
show message counts

### ISSUE THREAD

**Issue by rogpeppe** [zentures/sequence#8]
(First, thanks for this tool - it's potentially really useful)

When analysing a log file, it would be very useful to have
not only the patterns and the example line, but also the
number of lines in the log file that matched each pattern,
to get an idea for the prevalence of each pattern in the file.

**Comment by cryptix** [comment]
:+1: 
I thought about something similar. My idea was letting the `scanner` return the line number of the rules file it matched against or maybe adding an identifier to the rules to group them together.

**Comment by zhenjl** [comment]
Ack. I think someone else on reddit or HN also asked for something similar. Traveling last and this week (MWC) so won't be able to do much...but sounds like a good feature to have so will add.

**Comment by zhenjl** [comment]
In the analyze output I've added a comment showing the # of messages matching that pattern. Let me know if that works. 

I didn't list out every message that matches the pattern, but it's not hard to do if that's useful.
